### ISSUE TITLE
Undersoce character not visible after 2x zoom-in

### ISSUE THREAD

**Issue by Taskkill** [terminalpp/terminalpp#12]
Ubuntu 19.10

When you press `Ctrl +` to zoom in 2 times underscore (`_`) character disappears.

If you zoom-in one more time it is again visible. Same if you just revert the zoom level back to the non-2-level zoom-in. (Only 2x zoom is problematic for me.)

I don't know about any other character with the same problem.

**Comment by zduka** [comment]
Repro on WSL too with default fonts.
