### ISSUE TITLE
htop crashing

### ISSUE THREAD

**Issue by ivosu** [terminalpp/terminalpp#14]
While running htop and moving mouse (especially hovering over some text or when randomly some text "jumps under" cursor) the htop window just closes.
While being ssh-ed into my Raspberry Pi when this happens, some escaped character sequence get's printed. 

Tested on Linux Mint 19.3, Cinnamon, latest deb package. Windows version works just fine, but htop doesn't seem to care about mouse there.

**Comment by zduka** [comment]
Thanks! Turns out the terminal was incorrectly sending also mouse movement events which `htop` does not process.
