### ISSUE TITLE
Make a portable distribution available

### ISSUE THREAD

**Issue by phgmacedo** [terminalpp/terminalpp#28]
I would like to have a portable zip package so that it can be installed from [scoop](https://github.com/lukesampson/scoop-extras)

**Comment by zduka** [comment]
I'll have to familiarize with scoop first, but after a quick glance, this should not be a problem and will be added in next release. Thanks!

**Comment by zduka** [comment]
Windows portable distribution and scoop JSON added to releases starting from 0.8.4.
