### ISSUE TITLE
Possible incompatibility with ncurses

### ISSUE THREAD

**Issue by ivosu** [terminalpp/terminalpp#5]
While using some ncurses applications there seem to be issue with rendering. Some symbols (dis)appear or flicker.
Example of project best showcasing this issue is nInvaders (`sudo apt-get install ninvaders`). Tested on Linux Mint.

**Comment by zduka** [comment]
There may in theory be other missing escape sequences as `terminalpp` does not support the full `xterm-256` terminfo, but `ninvaders` should now work as intended.
